# https://wiki.hypr.land/Hypr-Ecosystem/hyprpaper/

##; START HOSTS; LAPTOP
wallpaper {
	monitor    = eDP-1
	path       = /home/sincos/Pictures/Wallpaper/pixel-art/dark-cat-rosewater.png
	fit_mode   = contain
}
##; END HOSTS; LAPTOP

##; START HOSTS; DESKTOP
wallpaper {
	monitor    = DP-3
	path       = /home/sincos/Pictures/Wallpaper/pixel-art/dark-cat-rosewater.png
	fit_mode   = contain
}

wallpaper {
	monitor    = DP-2
	path       = /home/sincos/Pictures/Wallpaper/pixel-art/dark-cat-rosewater.png
	fit_mode   = contain
}
##; END HOSTS; DESKTOP
