# https://wiki.hypr.land/Hypr-Ecosystem/hyprlock/

source = ~/.config/hypr/hyprlock/colors.conf

background {
	monitor       =
	path          = /home/sincos/Pictures/Wallpaper/pixel-art/dark-cat-rosewater.png
	blur_passes   = 2
}

general {
	no_fade_in            = false
	no_fade_out           = false
	hide_cursor           = true
	grace                 = 0
	disable_loading_bar   = true
	ignore_empty_input    = true
}

input-field {
	monitor             =
	size                = 200, 50
	outline_thickness   = 3
	dots_size           = 0.33
	dots_spacing        = 0.15
	dots_center         = true
	dots_rounding       = -1
	outer_color         = rgb($hl_accent)
	inner_color         = rgb($hl_bg)
	font_color          = rgb($hl_accent)
	fade_on_empty       = true
	fade_timeout        = 1000
	placeholder_text    = <i>Input Password...</i>
	hide_input          = false
	rounding            = -1
	check_color         = rgb($hl_check)
	fail_color          = rgb($hl_fail)
	fail_text           = <i>$FAIL <b>($ATTEMPTS)</b></i>
	fail_transition     = 100
	capslock_color      = -1
	numlock_color       = -1
	bothlock_color      = -1
	invert_numlock      = false
	swap_font_color     = false
	position            = 0, -20
	halign              = center
	valign              = center
}

### DATE & TIME ###

label {
  monitor       =
  text          = cmd[update:1000] date +"%A, %B %d"
  color         = rgba($hl_accent)
  font_size     = 22
  font_family   = Fira Semibold
  position      = 0, 300
  halign        = center
  valign        = center
}

label {
  monitor       =
  text          = cmd[update:1000]  date +"%-I:%M"
  color         = rgba($hl_accent)
  font_size     = 95
  font_family   = Fira Semibold
  position      = 0, 200
  halign        = center
  valign        = center
}
