### PROGRAMS ###

$terminal = kitty
$fileManager = thunar

##; START HOSTS; DESKTOP
$browser = firefox
##; END HOSTS; DESKTOP

##; START HOSTS; LAPTOP
$browser = firefox-nightly
##; END HOSTS; LAPTOP

$colorPicker = hyprpicker
$passManager = keepassxc

### 1. STATUS BAR & NOTIFICATIONS ###
### 2. SYS TRAY APPLETS ###
### 3. CLIPBOARD ###
### 4. AUTH & SESSION ###
### 5. WP, LOCK SCREEN, FILTER ###

exec-once = waybar
exec-once = dunst

exec-once = nm-applet --indicator
exec-once = blueman-applet

exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = wl-clip-persist --clipboard regular

exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = dbus-update-activation-environment --all

exec-once = hyprpaper
exec-once = hypridle
exec-once = hyprsunset
