### PROGRAMS ###

$terminal = kitty
$fileManager = thunar

##; START HOSTS; DESKTOP
$browser = firefox
##; END HOSTS; DESKTOP

##; START HOSTS; LAPTOP
$browser = firefox-nightly
##; END HOSTS; LAPTOP

$colorPicker = hyprpicker
$passManager = keepassxc
