### FLOATING WINDOWS ###

windowrule = float on,   match:class ^(kvantummanager)$
windowrule = float on,   match:class ^(qt5ct)$
windowrule = float on,   match:class ^(qt6ct)$
windowrule = float on,   match:class ^(nwg-look)$
windowrule = float on,   match:class ^(pavucontrol)$
windowrule = float on,   match:class ^(blueman-manager)$
windowrule = float on,   match:class ^(nm-applet)$
windowrule = float on,   match:class ^(nm-connection-editor)$
windowrule = float on,   match:class ^(polkit-gnome-authentication-agent-1)$

### LAYER RULES ###

layerrule = ignore_alpha 0,   match:namespace ^(rofi)$
layerrule = ignore_alpha 0,   match:namespace ^(dunst)$
layerrule = blur on,          match:namespace ^(dunst)$
