### 1. IGNORE MAXIMIZE REQS FROM APPS ###
### 2. FIX DRAGGING ISSUES WITH XWAYLAND ###
### 3. FIX JETBRAINS IDES DROPDOWNS FLICKERING ###

windowrule = suppress_event maximize,   match:class .*
windowrule = no_focus on,               match:class ^$,                  match:title ^$,       match:xwayland true,   match:float true,   match:fullscreen false,   match:pin false
windowrule = no_initial_focus on,       match:class ^(.*jetbrains.*)$,   match:title ^(win[0-9]+)$

### FLOATING WINDOWS ###

windowrule = float on,   match:class ^(kvantummanager)$
windowrule = float on,   match:class ^(qt5ct)$
windowrule = float on,   match:class ^(qt6ct)$
windowrule = float on,   match:class ^(nwg-look)$
windowrule = float on,   match:class ^(pavucontrol)$
windowrule = float on,   match:class ^(blueman-manager)$
windowrule = float on,   match:class ^(nm-applet)$
windowrule = float on,   match:class ^(nm-connection-editor)$
windowrule = float on,   match:class ^(polkit-gnome-authentication-agent-1)$

### LAYER RULES ###

layerrule = ignore_alpha 0,   match:namespace ^(rofi)$
layerrule = ignore_alpha 0,   match:namespace ^(dunst)$
layerrule = blur on,          match:namespace ^(dunst)$
